/*
 * This source file was generated by the Gradle 'init' task
 */

package bcc.unitConverter;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Unit Converter");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // the first parameter is rows, second is columns, third is horizontal gap,
        // fourth is vertical gap
        // when you add your new converter calculators, you will want to change the row
        // number from 1 to 2/3
        frame.setLayout(new GridLayout(1, 4, 5, 5));

        JLabel inputLabel1 = new JLabel("Fahrenheit:");
        JTextField inputField1 = new JTextField();
        JButton convertButton1 = new JButton("Convert");
        JLabel outputLabel1 = new JLabel("Celsius: ");

        // the below code uses what is called a try catch statatement.
        // if the code within the try block throws an error, the code within the catch
        // block will be executed
        // In this case, if the user inputs something that is not a number, parseDouble
        // will throw an error
        // If the user inputs something that is not a number, now instead of crashing,
        // instead they will get an error message.
        // try this out!
        convertButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    double fahrenheit = Double.parseDouble(inputField1.getText());
                    double celsius = (fahrenheit - 32) * 5 / 9;
                    // the user likely doesn't want a 15 digit print out of the conversion
                    //String.format allows you to format the output of a string to something more readable
                    // in this case, we are formatting it to 2 decimal places
                    // learn more at https://www.w3schools.com/java/ref_string_format.asp
                    outputLabel1.setText(String.format("Celsius: %.2f", celsius));
                } catch (NumberFormatException ex) {
                    outputLabel1.setText("Celsius: Invalid input");
                }
            }
        });

        frame.add(inputLabel1);
        frame.add(inputField1);
        frame.add(convertButton1);
        frame.add(outputLabel1);

        //add your other rows to the frame here

        //you will also want to change the size of the frame when you add more rows
        frame.setSize(500, 80);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

}
